# Generated by Django 3.0 on 2020-03-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contacted', models.BooleanField()),
                ('notes', models.TextField()),
                ('created_At', models.DateTimeField(auto_now=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
