# Generated by Django 3.0 on 2020-03-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
