# Generated by Django 3.0 on 2020-03-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_manager', '0002_auto_20200326_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='contacted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
